POST http://localhost:8090/login HTTP/1.1
Content-Type: application/json

{
  "username": "berk",
  "password": "123"
}

###

GET http://localhost:8090/demo HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJiZXJrIiwiaWF0IjoxNzIwNTU5ODgxLCJleHAiOjE3MjA2NDYyODF9.TkW9mSyqSxfco5Pw0TRK1hwkVqIn7JhRGsWEowuSER1rg2I2H5Ycc-69rxs8VqAh

###

POST http://localhost:8090/register HTTP/1.1
Content-Type: application/json

{
  "username": "berk",
  "password": "123",
  "firstName":"mertay",
  "lastName":"han",
  "role":"USER"
}

###
